posts:
- title: Ashamnu
  slug: ashamnu.html
  teaser: I recorded this song on GarageBand in 2009. It is an interpretation of a prayer recited on Rosh Hashanah and Yom Kippur, commonly known as <a target="blank" href="http://en.wikipedia.org/wiki/Confession_in_Judaism#Ashamnu.2C_the_short_confession">Ashamnu</a>&hellip;
- title: Is Tiger Winning?
  slug: istigerwinning.html
  teaser: Watching the 2013 US Open with some casual golf fans, I realized they only wanted one question answered. With that in mind, I built <a href="http://www.istigerwinning.com" target="_blank">www.IsTigerWinning.com</a>&hellip;